# Generated by Django 5.2.4 on 2025-07-30 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="urlcheck",
            new_name="api_urlchec_batch_i_7c26ad_idx",
            old_name="api_urlchec_batch_i_0e6ed4_idx",
        ),
        migrations.RenameIndex(
            model_name="urlcheck",
            new_name="api_urlchec_checked_afa263_idx",
            old_name="api_urlchec_checked_5e6ed4_idx",
        ),
    ]
